# Generated by Django 5.1.6 on 2025-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, unique=True)),
                ('ingredients', models.TextField()),
                ('direction', models.TextField()),
                ('servings', models.CharField(max_length=50)),
            ],
        ),
    ]
