# Generated by Django 5.1.6 on 2025-03-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_direction_remove_recipe_servings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='directions_embedding',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_embedding',
        ),
    ]
